"""
agents/researcher.py
--------------------
Research agent.

Responsibilities:
  - Receive ReportPlan
  - Research each research question
  - Use ResearchToolkit when available
  - Collect findings + sources
  - Return structured ResearchResult
  
Business Summary: Goes out and gathers the facts. 
Answers the specific questions generated by the Planner. 
It works with the Tools department to use web search if available.
Logic: Loops through research_questions. 
Calls the ResearchToolkit to get web search results (if enabled). 
Sends the questions and search context to the LLM. 
The LLM synthesizes the findings and cites sources. 
Returns structured ResearchResult per question.
"""

from __future__ import annotations

import json
from typing import Any, List, Optional

from agents import create_chat_agent
from models import ReportPlan, ResearchResult
from prompts import RESEARCHER_SYSTEM, build_researcher_prompt
from tools import ResearchToolkit, get_research_toolkit
from utils import (
    get_logger,
    log_error,
    log_event,
    message_content_to_str,
    parse_json_to_model,
)

logger = get_logger(__name__)

AGENT_NAME = "researcher"


def get_researcher_agent() -> Any:
    """Create the Research agent."""
    return create_chat_agent(
        name=AGENT_NAME,
        instructions=RESEARCHER_SYSTEM,
    )


def _question_texts(plan: ReportPlan) -> List[str]:
    return [
        rq.question
        for rq in plan.research_questions
        if rq.question and rq.question.strip()
    ]


def _normalize_research(result: ResearchResult, plan: ReportPlan) -> ResearchResult:
    """Attach plan and fill gaps from planned questions."""
    result.plan = plan

    by_id = {item.question_id: item for item in result.items if item.question_id}
    plan_q = {rq.id: rq for rq in plan.research_questions}

    for item in result.items:
        rq = plan_q.get(item.question_id)
        if rq:
            if not item.question:
                item.question = rq.question
            if not item.related_section_id and rq.related_section_id:
                item.related_section_id = rq.related_section_id

    missing = [rq.id for rq in plan.research_questions if rq.id not in by_id]
    if missing:
        logger.warning(
            "Research result missing %d question(s): %s",
            len(missing),
            ", ".join(missing),
        )

    return result


async def run_researcher(
    plan: ReportPlan,
    agent: Optional[Any] = None,
    toolkit: Optional[ResearchToolkit] = None,
) -> ResearchResult:
    """Execute research for the given ReportPlan."""
    if plan is None:
        raise ValueError("ReportPlan is required for research.")

    questions = plan.research_questions or []
    log_event(
        "research_started",
        title=plan.title,
        questions=len(questions),
    )

    if not questions:
        log_event("research_skipped_no_questions", title=plan.title)
        return ResearchResult(
            items=[],
            additional_notes="No research questions were provided in the plan.",
            plan=plan,
        )

    research_toolkit = toolkit or get_research_toolkit()
    tool_results_text = research_toolkit.gather_for_questions(_question_texts(plan))

    main_topic = ""
    if plan.analyzed_request is not None:
        main_topic = plan.analyzed_request.main_topic

    research_questions_json = json.dumps(
        [rq.model_dump(mode="json") for rq in plan.research_questions],
        indent=2,
        default=str,
    )

    user_prompt = build_researcher_prompt(
        report_title=plan.title,
        scope=plan.scope or "",
        research_questions_json=research_questions_json,
        main_topic=main_topic,
        tool_results=tool_results_text,
    )

    chat_agent = agent or get_researcher_agent()

    try:
        result = await chat_agent.run(user_prompt)
        raw_text = message_content_to_str(getattr(result, "text", None) or result)
    except Exception as exc:  # noqa: BLE001
        log_error("research_llm_failed", exc)
        raise RuntimeError(f"Researcher LLM call failed: {exc}") from exc

    try:
        research = parse_json_to_model(raw_text, ResearchResult)
    except ValueError as exc:
        log_error("research_parse_failed", exc, raw_preview=raw_text[:500])
        raise ValueError(
            f"Researcher returned invalid structured output: {exc}"
        ) from exc

    research = _normalize_research(research, plan)

    log_event(
        "research_completed",
        title=plan.title,
        items=len(research.items),
        tools_used=research_toolkit.any_available(),
    )
    return research


def run_researcher_sync(
    plan: ReportPlan,
    agent: Optional[Any] = None,
    toolkit: Optional[ResearchToolkit] = None,
) -> ResearchResult:
    """Synchronous wrapper for scripts/tests."""
    import asyncio

    return asyncio.run(run_researcher(plan, agent=agent, toolkit=toolkit))